name: Build Flutter APK

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: cd ./decision_making_app;flutter pub get
      #- run: cd ./decision_making_app;dart format --set-exit-if-changed .
      #- run: cd ./decision_making_app;flutter analyze .
      - run: cd ./decision_making_app;flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: decision_making_app/build/app/outputs/flutter-apk/
