name: test-decision-making-app
on: [push, workflow_dispatch]
jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - run: cd ./decision_making_app;flutter test;cd ..
